name: MiFilzaPro
options:
  bundleIdPrefix: com.elvis
  deploymentTarget:
    iOS: "14.0"
targets:
  MiFilzaPro:
    type: application
    platform: iOS
    sources:
      - path: MiApp
    settings:
      base:
        INFOPLIST_FILE: MiApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.elvis.mifilzapro
        CODE_SIGNING_ALLOWED: NO
